name: "FAP Build"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build FAP
        run: |
          python3 -m pip install --upgrade ufbt
          ufbt build

      - name: List FAP location
        run: |
          find /home/runner/ufbt -name "*.fap" -type f

      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: servo_control
          path: /home/runner/ufbt/build/servo_control_dir/servo_control.fap
          if-no-files-found: warn
